name: "Pull Request Labeler"
on:
  pull_request_target:

jobs:
  label:
    runs-on: windows-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Labeler
      uses: actions/labeler@v3
      with:
        repo-token: "${{ secrets.Update }}"
